// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcdpwbaaltoxiagnearl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZHB3YmFhbHRveGlhZ25lYXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mjc1NjgsImV4cCI6MjA2NzIwMzU2OH0.WFPXrwVPeXfNtpj5jzNLMOrdZ0iPuyWWEs-LRXnisYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});